// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_omrP1EdahuHvJX5s0ufiRSi2qxNdf0',
    appId: '1:500380249110:web:ee5be4b4191c732cf3d937',
    messagingSenderId: '500380249110',
    projectId: 'quanlynhahang-d858b',
    authDomain: 'quanlynhahang-d858b.firebaseapp.com',
    databaseURL: 'https://quanlynhahang-d858b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlynhahang-d858b.firebasestorage.app',
    measurementId: 'G-3LR24R2F57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7u72t4Ak_dll4Qi_cmVOSFqbcHt1ZfI',
    appId: '1:500380249110:android:8068ea20b396bab2f3d937',
    messagingSenderId: '500380249110',
    projectId: 'quanlynhahang-d858b',
    databaseURL: 'https://quanlynhahang-d858b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlynhahang-d858b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxXfT3EgkaCaXG3dJL748ROgDEa8C3iDc',
    appId: '1:500380249110:ios:b74c404ccb983405f3d937',
    messagingSenderId: '500380249110',
    projectId: 'quanlynhahang-d858b',
    databaseURL: 'https://quanlynhahang-d858b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlynhahang-d858b.firebasestorage.app',
    iosBundleId: 'com.example.quanlynhahang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxXfT3EgkaCaXG3dJL748ROgDEa8C3iDc',
    appId: '1:500380249110:ios:b74c404ccb983405f3d937',
    messagingSenderId: '500380249110',
    projectId: 'quanlynhahang-d858b',
    databaseURL: 'https://quanlynhahang-d858b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlynhahang-d858b.firebasestorage.app',
    iosBundleId: 'com.example.quanlynhahang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_omrP1EdahuHvJX5s0ufiRSi2qxNdf0',
    appId: '1:500380249110:web:57976473dbb44c1ff3d937',
    messagingSenderId: '500380249110',
    projectId: 'quanlynhahang-d858b',
    authDomain: 'quanlynhahang-d858b.firebaseapp.com',
    databaseURL: 'https://quanlynhahang-d858b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quanlynhahang-d858b.firebasestorage.app',
    measurementId: 'G-M37NK2YG4Z',
  );
}
